package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.TeamEmployee;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TeamEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_EMPLOYEE
     *
     * @mbg.generated Wed May 18 13:38:54 EEST 2022
     */
    int insert(TeamEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_EMPLOYEE
     *
     * @mbg.generated Wed May 18 13:38:54 EEST 2022
     */
    List<TeamEmployee> selectAll();
}