package lt.vu.mybatis.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.EXTERNAL_ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    private Integer externalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.MANAGER_ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    private Integer managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.EXTERNAL_ID
     *
     * @return the value of PUBLIC.EMPLOYEE.EXTERNAL_ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public Integer getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.EXTERNAL_ID
     *
     * @param externalId the value for PUBLIC.EMPLOYEE.EXTERNAL_ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public void setExternalId(Integer externalId) {
        this.externalId = externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.NAME
     *
     * @param name the value for PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.MANAGER_ID
     *
     * @return the value of PUBLIC.EMPLOYEE.MANAGER_ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.MANAGER_ID
     *
     * @param managerId the value for PUBLIC.EMPLOYEE.MANAGER_ID
     *
     * @mbg.generated Wed May 18 11:08:02 EEST 2022
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }
}