package lt.vu.mybatis.model;

public class Team {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.ID
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.NAME
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.TEAMLEAD_ID
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    private Integer teamleadId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.ID
     *
     * @return the value of PUBLIC.TEAM.ID
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.ID
     *
     * @param id the value for PUBLIC.TEAM.ID
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.NAME
     *
     * @return the value of PUBLIC.TEAM.NAME
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.NAME
     *
     * @param name the value for PUBLIC.TEAM.NAME
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.TEAMLEAD_ID
     *
     * @return the value of PUBLIC.TEAM.TEAMLEAD_ID
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    public Integer getTeamleadId() {
        return teamleadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.TEAMLEAD_ID
     *
     * @param teamleadId the value for PUBLIC.TEAM.TEAMLEAD_ID
     *
     * @mbg.generated Tue May 17 19:34:23 EEST 2022
     */
    public void setTeamleadId(Integer teamleadId) {
        this.teamleadId = teamleadId;
    }
}